name: OAUTH2.APP
version: 0.1.00
description: Website.
author: Louise van der Lith
repository: https://github.com/louisevanderlith/oauth2
environment:
  sdk: '>=2.0.0 < 3.0.0'
dev_dependencies:
  build_runner: '>=1.0.0 <2.0.0'
  build_web_compilers: '>=1.0.0 <2.0.0'
dependencies:
  mango_ui: '^0.3.8'